server:
  port: 8890


spring:
  application:
    name: gateway-server


  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka