server:
  port: 8779


spring:
  application:
    name: rabbitmq-consumer
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        greetingChannel_output:
          destination: greetings
        greetingChannel_input:
          destination: greetings
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

