server:
  port: 9001


spring:
  application:
    name: feign-client

  cloud:
    config:
      discovery:
        service-id: config-server
      label: master
      profile: dev



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

