server:
  port: 9000


spring:
  application:
    name: openfeign-consumer



eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.85:8761/eureka


feign:
  hystrix:
    enabled: true

